global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'babylon-django-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'babylon-backend'
          environment: 'development'
